apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:8.1.4
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "labs"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_SMTP_ENABLED
              value: "false"
          ports:
          - name: grafana
            containerPort: 3000
      securityContext:
        fsGroup: 472

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
