# permissions for end users to view synthetictasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: synthetictask-viewer-role
rules:
- apiGroups:
  - synthetics.kentiklabs.com
  resources:
  - synthetictasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - synthetics.kentiklabs.com
  resources:
  - synthetictasks/status
  verbs:
  - get
