# permissions for end users to edit synthetictasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: synthetictask-editor-role
rules:
- apiGroups:
  - synthetics.kentiklabs.com
  resources:
  - synthetictasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synthetics.kentiklabs.com
  resources:
  - synthetictasks/status
  verbs:
  - get
