apiVersion: synthetics.kentiklabs.com/v1
kind: SyntheticTask
metadata:
  name: demo
spec:
  server_image: r.underland.io/kentik/synsrv:latest
  agent_image: r.underland.io/kentik/ksynth:latest
  fetch:
    - service: demo
      target: /
      port: 8080
      method: GET
      period: 30s
      expiry: 5s
