apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
spec:
  selector:
    matchLabels:
      app: influx
  replicas: 1
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
      - name: influx
        image: docker.io/library/influxdb:2.0
        env:
          - name: DOCKER_INFLUXDB_INIT_MODE
            value: "setup"
          - name: DOCKER_INFLUXDB_INIT_USERNAME
            value: "admin"
          - name: DOCKER_INFLUXDB_INIT_PASSWORD
            value: "influxdb"
          - name: DOCKER_INFLUXDB_INIT_ORG
            value: "system"
          - name: DOCKER_INFLUXDB_INIT_BUCKET
            value: "default"
          - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            value: "secret-token"
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
        ports:
        - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: influx
  labels:
    app: influx
spec:
  ports:
  - port: 8086
    name: http
    targetPort: 8086
  selector:
    app: influx
