name: Publish Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Set Version
        run: |
           echo VERSION=`date +"kt-%Y-%m-%d-${GITHUB_RUN_ID}-staging"` >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get install make golint

      - name: Run build
        run: |
          echo ${{ env.VERSION }}
          VERSION=${{ env.VERSION }} make

      - name: Run vet & lint
        run: |
          go vet .

      - name: Run testing
        run: make test

      - name: Build and Publish Docker
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: kentiklabs/odyssey-controller:staging
          build-args: |
            VERSION=${{ env.VERSION }}
